/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Kavya
 */
public class ProvidePrescriptionJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private PatientTreatmentWorkRequest request;

    /**
     * Creates new form ProvidePrescriptionJPanel
     */
    public ProvidePrescriptionJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, PatientTreatmentWorkRequest workRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.request = workRequest;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtMedicalCondition = new javax.swing.JTextField();
        txtAssignedDoctor = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 244, 244));
        setEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 79, 133));
        jLabel1.setText("Prescription Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 228, -1));

        jLabel6.setFont(new java.awt.Font("Skia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 79, 133));
        jLabel6.setText("Patient Information");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 220, 30));

        txtFirstName.setEditable(false);
        txtFirstName.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 131, 23));

        jLabel7.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 79, 133));
        jLabel7.setText("First Name :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 90, -1));

        jLabel10.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 79, 133));
        jLabel10.setText("Last Name :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 90, -1));

        txtLastName.setEditable(false);
        txtLastName.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 131, 23));

        jLabel8.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 79, 133));
        jLabel8.setText("Assigned Doctor Information :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 210, -1));

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 131, 23));

        jLabel27.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(2, 79, 133));
        jLabel27.setText("Age :");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 50, -1));

        jLabel3.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 79, 133));
        jLabel3.setText("Prescription:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 100, -1));

        txtPrescription.setColumns(20);
        txtPrescription.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        txtPrescription.setRows(5);
        jScrollPane1.setViewportView(txtPrescription);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 400, 86));

        jLabel4.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 79, 133));
        jLabel4.setText("Patient Medical Condition :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 190, -1));

        txtMedicalCondition.setEditable(false);
        txtMedicalCondition.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        add(txtMedicalCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 130, 23));

        txtAssignedDoctor.setEditable(false);
        txtAssignedDoctor.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        add(txtAssignedDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 131, 23));

        btnSubmit.setBackground(new java.awt.Color(2, 79, 133));
        btnSubmit.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 80, -1));

        backJButton.setBackground(new java.awt.Color(2, 79, 133));
        backJButton.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 11, 90, -1));

        jLabel2.setBackground(new java.awt.Color(245, 243, 243));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/drugs.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 290, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String prescription = txtPrescription.getText();
        if (prescription.equals("")) {
            JOptionPane.showMessageDialog(null, "Prescription cannot be blank");
            return;
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                request.setPrescription(prescription);
                request.setStatus("Prescription Provided");
                JOptionPane.showMessageDialog(null, "Prescription submitted successfully");
                btnSubmit.setEnabled(false);
            }
        }        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAssignedDoctor;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMedicalCondition;
    private javax.swing.JTextArea txtPrescription;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        txtFirstName.setText(request.getPatient().getPatientFirstName());
        txtLastName.setText(request.getPatient().getPatientLastName());
        txtAge.setText(String.valueOf(request.getPatient().getPatientAge()));
        txtMedicalCondition.setText(request.getReasonForVisit());
        txtAssignedDoctor.setText(request.getAssignedDoctor().getEmployee().getName());

    }
}
