/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.StudentOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ankitaindi
 */
public class RequestStudentAssistantshipJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientTreatmentWorkRequest patientTreatmentWorkRequest;

    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestStudentAssistantshipJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, PatientTreatmentWorkRequest patientTreatmentWorkRequest) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.patientTreatmentWorkRequest = patientTreatmentWorkRequest;
        valueLabel.setText(enterprise.getName());
        requestAssistantshipJButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestAssistantshipJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStudentMedicalPractice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(2, 79, 133));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestAssistantshipJButton.setBackground(new java.awt.Color(2, 79, 133));
        requestAssistantshipJButton.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        requestAssistantshipJButton.setForeground(new java.awt.Color(255, 255, 255));
        requestAssistantshipJButton.setText("Request Assistantship");
        requestAssistantshipJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestAssistantshipJButtonActionPerformed(evt);
            }
        });
        add(requestAssistantshipJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 200, 30));

        jLabel1.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 79, 133));
        jLabel1.setText("Message:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 70, -1));

        txtMessage.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 200, 30));

        backJButton.setBackground(new java.awt.Color(2, 79, 133));
        backJButton.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        valueLabel.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(2, 79, 133));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 130, 20));

        enterpriseLabel.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(2, 79, 133));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 80, 20));

        jLabel2.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 79, 133));
        jLabel2.setText("Student Medical Practice:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 180, -1));

        txtStudentMedicalPractice.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        add(txtStudentMedicalPractice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 200, 30));

        jLabel3.setFont(new java.awt.Font("Skia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 79, 133));
        jLabel3.setText("Student Assistantship Request");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestAssistantshipJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestAssistantshipJButtonActionPerformed

        String studentMedicalPractice = txtStudentMedicalPractice.getText().trim();
        String message = txtMessage.getText().trim();

        if (studentMedicalPractice.equals("")) {
            JOptionPane.showMessageDialog(null, "Lab Type cannot be blank");
            return;
        }
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message cannot be blank");
            return;
        }

        patientTreatmentWorkRequest.setLabTestMessage(message);
        patientTreatmentWorkRequest.setSender(userAccount);
        patientTreatmentWorkRequest.setStatus("SentToLab");
        patientTreatmentWorkRequest.setReceiver(null);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizations()) {
            if (organization instanceof StudentOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
            userAccount.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
            JOptionPane.showMessageDialog(null, "Student assistanship submitted successfully");
           txtMessage.setText("");
           txtStudentMedicalPractice.setText("");
           requestAssistantshipJButton.setEnabled(false);
        }

    }//GEN-LAST:event_requestAssistantshipJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton requestAssistantshipJButton;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtStudentMedicalPractice;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
