/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthcareAccountantRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HealthCenterEnterprise;
import Business.Enterprise.InsuranceCompanyEnterprise;
import Business.Insurance.Insurance;
import Business.InsuranceCustomer.InsuranceCustomer;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Kavya
 */
public class CreateAppointmentJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem ecosystem;
    private String patientId;

    /**
     * Creates new form CreateAppointmentJPanel
     */
    CreateAppointmentJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem ecoSystem, String patientId) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecoSystem;
        this.patientId = patientId;
        
        populateField();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        txtPatientId11 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPatientSSN = new javax.swing.JTextField();
        btnFindPatient = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtHomePhone = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        radioBtnMale = new javax.swing.JRadioButton();
        radioBtnFemale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        radioBtnPatientInsuranceYes = new javax.swing.JRadioButton();
        radioBtnPatientInsuranceNo = new javax.swing.JRadioButton();
        lblHavePolicy = new javax.swing.JLabel();
        lblPolicyName = new javax.swing.JLabel();
        lblInsCompany = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        txtReasonForVisit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblPolicyNum = new javax.swing.JLabel();
        txtPolicyNum = new javax.swing.JTextField();
        btnFindInsurance = new javax.swing.JButton();
        txtInsuranceCompany = new javax.swing.JTextField();
        txtPolicyName = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        lblCoverage = new javax.swing.JLabel();
        txtCoverage = new javax.swing.JTextField();
        radioBtnOther = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtPatientIdentifier = new javax.swing.JTextField();
        btnResetPolicyNum = new javax.swing.JButton();
        txtEmail = new javax.swing.JLabel();
        txtPatientEmail = new javax.swing.JTextField();

        jLabel14.setText("Middle Name :");

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(2, 79, 133));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Skia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 79, 133));
        jLabel1.setText("CREATE APPOINTMENT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 19, -1, 28));

        btnBack.setBackground(new java.awt.Color(2, 79, 133));
        btnBack.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 79, 133));
        jLabel2.setText("Already registered? Provide SSN: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, -1, -1));
        add(txtPatientSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 61, 138, -1));

        btnFindPatient.setBackground(new java.awt.Color(2, 79, 133));
        btnFindPatient.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        btnFindPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnFindPatient.setText("Find Patient");
        btnFindPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPatientActionPerformed(evt);
            }
        });
        add(btnFindPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 65, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 79, 133));
        jLabel3.setText("Date:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 71, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Skia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 79, 133));
        jLabel6.setText("PATIENT INFORMATION");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 231, -1));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 140, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 79, 133));
        jLabel7.setText("First Name :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 79, 133));
        jLabel8.setText("Address:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 79, 133));
        jLabel10.setText("Last Name :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 146, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(2, 79, 133));
        jLabel17.setText("SSN :");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 145, -1));

        txtHomePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomePhoneActionPerformed(evt);
            }
        });
        add(txtHomePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 140, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(2, 79, 133));
        jLabel18.setText("Phone Number:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 56, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(2, 79, 133));
        jLabel24.setText("Age :");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(2, 79, 133));
        jLabel25.setText("Sex :");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        radioBtnMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(radioBtnMale);
        radioBtnMale.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        radioBtnMale.setForeground(new java.awt.Color(2, 79, 133));
        radioBtnMale.setText("M");
        radioBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMaleActionPerformed(evt);
            }
        });
        add(radioBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        radioBtnFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(radioBtnFemale);
        radioBtnFemale.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        radioBtnFemale.setForeground(new java.awt.Color(2, 79, 133));
        radioBtnFemale.setText("F");
        radioBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFemaleActionPerformed(evt);
            }
        });
        add(radioBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Skia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 79, 133));
        jLabel9.setText("INSURANCE INFORMATION");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, -1, -1));

        radioBtnPatientInsuranceYes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioBtnPatientInsuranceYes);
        radioBtnPatientInsuranceYes.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        radioBtnPatientInsuranceYes.setForeground(new java.awt.Color(2, 79, 133));
        radioBtnPatientInsuranceYes.setText("Yes");
        radioBtnPatientInsuranceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPatientInsuranceYesActionPerformed(evt);
            }
        });
        add(radioBtnPatientInsuranceYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, -1, -1));

        radioBtnPatientInsuranceNo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioBtnPatientInsuranceNo);
        radioBtnPatientInsuranceNo.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        radioBtnPatientInsuranceNo.setForeground(new java.awt.Color(2, 79, 133));
        radioBtnPatientInsuranceNo.setText("No");
        radioBtnPatientInsuranceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPatientInsuranceNoActionPerformed(evt);
            }
        });
        add(radioBtnPatientInsuranceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, -1, -1));

        lblHavePolicy.setBackground(new java.awt.Color(255, 255, 255));
        lblHavePolicy.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        lblHavePolicy.setForeground(new java.awt.Color(2, 79, 133));
        lblHavePolicy.setText("Is this patient covered by Insurance");
        add(lblHavePolicy, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));

        lblPolicyName.setBackground(new java.awt.Color(255, 255, 255));
        lblPolicyName.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        lblPolicyName.setForeground(new java.awt.Color(2, 79, 133));
        lblPolicyName.setText("Policy Name :");
        add(lblPolicyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 320, -1, -1));

        lblInsCompany.setBackground(new java.awt.Color(255, 255, 255));
        lblInsCompany.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        lblInsCompany.setForeground(new java.awt.Color(2, 79, 133));
        lblInsCompany.setText("Insurance Company :");
        add(lblInsCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));

        btnCreate.setBackground(new java.awt.Color(2, 79, 133));
        btnCreate.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 105, 33));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(2, 79, 133));
        jLabel34.setText("Reason for Visit:");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));
        add(txtReasonForVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 269, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 405, 65));

        lblPolicyNum.setBackground(new java.awt.Color(255, 255, 255));
        lblPolicyNum.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        lblPolicyNum.setForeground(new java.awt.Color(2, 79, 133));
        lblPolicyNum.setText("Provide Insurance Policy Number:");
        add(lblPolicyNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        txtPolicyNum.setEnabled(false);
        add(txtPolicyNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 139, -1));

        btnFindInsurance.setBackground(new java.awt.Color(2, 79, 133));
        btnFindInsurance.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        btnFindInsurance.setForeground(new java.awt.Color(255, 255, 255));
        btnFindInsurance.setText("Find Policy");
        btnFindInsurance.setEnabled(false);
        btnFindInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindInsuranceActionPerformed(evt);
            }
        });
        add(btnFindInsurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, -1, -1));
        add(txtInsuranceCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 137, -1));
        add(txtPolicyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 320, 183, -1));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 64, 130, -1));

        lblCoverage.setBackground(new java.awt.Color(255, 255, 255));
        lblCoverage.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        lblCoverage.setForeground(new java.awt.Color(2, 79, 133));
        lblCoverage.setText("Patient Insurance Coverage % :");
        add(lblCoverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));
        add(txtCoverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 137, -1));

        radioBtnOther.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(radioBtnOther);
        radioBtnOther.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        radioBtnOther.setForeground(new java.awt.Color(2, 79, 133));
        radioBtnOther.setText("Other");
        add(radioBtnOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 79, 133));
        jLabel4.setText("Patient ID / Visit ID :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 106, -1, -1));
        add(txtPatientIdentifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 99, 138, -1));

        btnResetPolicyNum.setBackground(new java.awt.Color(2, 79, 133));
        btnResetPolicyNum.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        btnResetPolicyNum.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPolicyNum.setText("Reset Policy Number");
        btnResetPolicyNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPolicyNumActionPerformed(evt);
            }
        });
        add(btnResetPolicyNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 280, -1, -1));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(2, 79, 133));
        txtEmail.setText("Patient Email:");
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 119, -1, -1));
        add(txtPatientEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 112, 234, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtHomePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomePhoneActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void radioBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnMaleActionPerformed

    private void radioBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnFemaleActionPerformed

    private void radioBtnPatientInsuranceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPatientInsuranceYesActionPerformed
        lblPolicyNum.setEnabled(true);
        btnFindInsurance.setEnabled(true);
        txtPolicyNum.setEnabled(true);

    }//GEN-LAST:event_radioBtnPatientInsuranceYesActionPerformed

    private void radioBtnPatientInsuranceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPatientInsuranceNoActionPerformed
        
        lblPolicyNum.setEnabled(false);
        btnFindInsurance.setEnabled(false);
        txtPolicyNum.setEnabled(false);
        txtInsuranceCompany.setEnabled(false);
        txtPolicyName.setEnabled(false);
        
        txtCoverage.setEnabled(false);
        
        lblCoverage.setEnabled(false);
        lblInsCompany.setEnabled(false);
        
        lblPolicyName.setEnabled(false);
    }//GEN-LAST:event_radioBtnPatientInsuranceNoActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        
        if (txtFirstName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide first name");
            return;
        }
        if (txtLastName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide last name");
            return;
        }
        if (buttonGroup2.isSelected(null)) {
            JOptionPane.showMessageDialog(null, "Please select gender");
            return;
        }
        if (txtHomePhone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide phone");
            return;
        }
        if (txtSSN.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide SSN");
            return;
        }
        if (txtAge.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide age");
            return;
        }
        if (txtAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide address");
            return;
        }
        
        if (buttonGroup1.isSelected(null)) {
            JOptionPane.showMessageDialog(null, "Please choose if Patient covered by Insurance");
            return;
        }
        
        if (txtReasonForVisit.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide Reason for visit");
            return;
            
        }
        if (txtPatientEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide an Email ID");
            return;
            
        }
        if (!usernamePatternCorrect(txtPatientEmail.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Please provide a valid email ID in the format xxxx@xx.xx");
            
        }
        else {
            
            String registrationDate = txtDate.getText().trim();
            
            String firstName = txtFirstName.getText().trim();
            String lastName = txtLastName.getText().trim();
            String gender = "Male";
            if (radioBtnFemale.isSelected()) {
                gender = "Female";
            } else if (radioBtnOther.isSelected()) {
                gender = "Other";
            }
            
            String phoneNo = txtHomePhone.getText().trim();
            
            if (!phonePatternCorrect()) {
                JOptionPane.showMessageDialog(null, "/* Following are valid phone number examples */             \n"
                        + "              \"1234567890\", \"123-456-7890\", \"(123)4567890\", \"(123)456-7890\",\n"
                        + "              /* Following are invalid phone numbers */ \n"
                        + "              \"(1234567890)\",\"123)4567890\", \"12345678901\", \"(1)234567890\",");
                txtHomePhone.setBorder(BorderFactory.createLineBorder(Color.RED));
                
                return;
            }
            
            if (phonePatternCorrect()) {
                txtHomePhone.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                
            }
            
            String ssn = txtSSN.getText().trim();
            
            if (!ssnPatternCheck()) {
                JOptionPane.showMessageDialog(null, "/* United States Social Security numbers are nine-digit numbers in the format AAA-GG-SSSS with following rules. */             \n"
                        + "              \"The first three digits called the area number. The area number cannot be 000, 666, or between 900 and 999\",\n"
                        + "                \" Digits four and five are called the group number and range from 01 to 99\",\n"
                        + "              \"The last four digits are serial numbers from 0001 to 9999.\"");
                txtSSN.setBorder(BorderFactory.createLineBorder(Color.RED));
                
                return;
            }
            
            if (ssnPatternCheck()) {
                txtSSN.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                
            }
            
            String age = txtAge.getText().trim();
            
            try {
                Integer.parseInt(age);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please provide integer values in Age textfield");
                return;
            }
            
            String address = txtAddress.getText().trim();
            boolean hasInsurance = false;
            
            String policyNumber = txtPolicyNum.getText().trim();
            if (radioBtnPatientInsuranceYes.isSelected()) {
                if (policyNumber.equals("")) {
                    JOptionPane.showMessageDialog(null, "Provide policy number");
                    return;
                }
                
                if (txtPolicyName.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "No Policy found, please provide correct policy number");
                    return;
                }
            }
            String insuranceCompany = String.valueOf(txtInsuranceCompany.getText());
            String policyName = String.valueOf(txtPolicyName.getText());
            String coverString = txtCoverage.getText().trim();
            double coverage = coverString.equals("") ? 0 : Double.parseDouble(txtCoverage.getText().trim());
            
            String reasonForVisit = txtReasonForVisit.getText().trim();
            
            if (hasInsurance) {
                if (txtPolicyNum.getText().equals("")) {
                    return;
                }
            }
            
            Insurance insurance = new Insurance(policyName, insuranceCompany, coverage);
            InsuranceCustomer insuranceCustomer = new InsuranceCustomer(insurance, policyNumber);
            
            HealthCenterEnterprise healthCenterEnterprise = (HealthCenterEnterprise) enterprise;
            Patient patient = new Patient();
            
            patient.setAppointmentDate(txtDate.getText());
            patient.setPatientId(patientId);
            patient.setPatientFirstName(firstName);
            patient.setPatientLastName(lastName);
            patient.setGender(gender);
            patient.setPatientEmail(txtPatientEmail.getText().trim());
            
            patient.setContactNumber(phoneNo);
            patient.setPatientAge(age);
            patient.setSocialSecurityNumber(ssn);
            patient.setAddress(address);
            
            patient.setInsuranceCustomer(insuranceCustomer);
            
            healthCenterEnterprise.getPatientDirectory().getPatients().add(patient);
            
            PatientTreatmentWorkRequest patientTreatmentWorkRequest = new PatientTreatmentWorkRequest(registrationDate, reasonForVisit, patient);
            patientTreatmentWorkRequest.setStatus("Waiting for Doctor");
            //   patientTreatmentWorkRequest.setSender(userAccount);

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizations()) {
                if (organization instanceof DoctorOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
                userAccount.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
                refresh();
                JOptionPane.showMessageDialog(null, "Patient Registered Successfully");
            }
            
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AccountantWorkAreaJPanel dwjp = (AccountantWorkAreaJPanel) component;
        dwjp.populateAllPatientsTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFindPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPatientActionPerformed
        
        boolean isPatientFound = false;
        String ssn = txtPatientSSN.getText().trim();
        List<Network> networks = ecosystem.getNetworks();
        List<HealthCenterEnterprise> healthCenterEnterprises = new ArrayList<>();
        
        for (Network network : networks) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HealthCenterEnterprise) {
                    healthCenterEnterprises.add((HealthCenterEnterprise) enterprise);
                }
            }
        }
        
        for (HealthCenterEnterprise healthCenterEnterprise : healthCenterEnterprises) {
            List<Patient> patients = healthCenterEnterprise.getPatientDirectory().getPatients();
            for (Patient patient : patients) {
                if (ssn.equals(patient.getSocialSecurityNumber())) {
                    autopopulateFields(patient);
                    isPatientFound = true;
                }
                
            }
        }
        
        if (!isPatientFound) {
            JOptionPane.showMessageDialog(null, "No patient Found");
        }
    }//GEN-LAST:event_btnFindPatientActionPerformed

    private void btnFindInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindInsuranceActionPerformed
        String insurancePolicyNumber = txtPolicyNum.getText().trim();
        String ssn = txtSSN.getText().trim();
        List<InsuranceCompanyEnterprise> insuranceEnterprises = new ArrayList<>();
        InsuranceCustomer matchedCustomer = null;
        
        List<Network> networks = ecosystem.getNetworks();
        for (Network network : networks) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof InsuranceCompanyEnterprise) {
                    insuranceEnterprises.add((InsuranceCompanyEnterprise) enterprise);
                }
            }
        }
        
        for (InsuranceCompanyEnterprise insuranceCompanyEnterprise : insuranceEnterprises) {
            List<InsuranceCustomer> insuranceCustomers = insuranceCompanyEnterprise.getInsuranceCustomerDirectory().getInsuranceCustomers();
            for (InsuranceCustomer insuranceCustomer : insuranceCustomers) {
                if (insurancePolicyNumber.equals(insuranceCustomer.getInsurancePolicyNumber()) && ssn.equals(insuranceCustomer.getSsn())) {
                    matchedCustomer = insuranceCustomer;
                    
                }
            }
        }
        
        if (matchedCustomer != null) {
            txtInsuranceCompany.setText(matchedCustomer.getInsurance().getInsuranceCompany());
            txtPolicyName.setText(matchedCustomer.getInsurance().getPolicyName());
            //  txtPolicyNo.setText(matchedCustomer.getInsurancePolicyNumber());
            txtCoverage.setText(String.valueOf(matchedCustomer.getInsurance().getCoverage()));
            txtPolicyNum.setEnabled(false);
            txtSSN.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Policy number does not match with provided SSN");
            txtInsuranceCompany.setText("");
            txtPolicyName.setText("");
            txtCoverage.setText("");
            txtPolicyNum.setText("");
            return;
        }
    }//GEN-LAST:event_btnFindInsuranceActionPerformed

    private void btnResetPolicyNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPolicyNumActionPerformed
        txtPolicyNum.setEnabled(true);
        txtSSN.setEnabled(true);
        txtPolicyNum.setText("");
        txtPolicyName.setText("");
        txtInsuranceCompany.setText("");
        txtCoverage.setText("");
        

    }//GEN-LAST:event_btnResetPolicyNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnFindInsurance;
    private javax.swing.JButton btnFindPatient;
    private javax.swing.JButton btnResetPolicyNum;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCoverage;
    private javax.swing.JLabel lblHavePolicy;
    private javax.swing.JLabel lblInsCompany;
    private javax.swing.JLabel lblPolicyName;
    private javax.swing.JLabel lblPolicyNum;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JRadioButton radioBtnOther;
    private javax.swing.JRadioButton radioBtnPatientInsuranceNo;
    private javax.swing.JRadioButton radioBtnPatientInsuranceYes;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCoverage;
    private javax.swing.JTextField txtDate;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHomePhone;
    private javax.swing.JTextField txtInsuranceCompany;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextField txtPatientId11;
    private javax.swing.JTextField txtPatientIdentifier;
    private javax.swing.JTextField txtPatientSSN;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyNum;
    private javax.swing.JTextField txtReasonForVisit;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables

    private void populateField() {
        LocalDateTime localTimeUpdate = LocalDateTime.now();
        DateTimeFormatter dateTimeFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy hh:mm:ss");
        txtDate.setText(localTimeUpdate.format(dateTimeFormat));
        
        txtPatientIdentifier.setText(patientId);
        
        lblPolicyNum.setEnabled(false);
        btnFindInsurance.setEnabled(false);
        txtPolicyNum.setEnabled(false);
        txtInsuranceCompany.setEnabled(false);
        txtPolicyName.setEnabled(false);
        
        txtCoverage.setEnabled(false);
        
        lblCoverage.setEnabled(false);
        lblInsCompany.setEnabled(false);
        
        lblPolicyName.setEnabled(false);
    }
    
    private void refresh() {
        
        txtPatientIdentifier.setText(UUID.randomUUID().toString().substring(0, 7));
        txtFirstName.setText("");
        txtLastName.setText("");
        txtHomePhone.setText("");
        txtAge.setText("");
        txtSSN.setText("");
        txtAddress.setText("");
        txtReasonForVisit.setText("");
        txtPatientEmail.setText("");
        txtPolicyName.setText("");
        txtPolicyNum.setText("");
        txtCoverage.setText("");
        txtInsuranceCompany.setText("");
    }
    
    private boolean phonePatternCorrect() {
        
        Pattern pattern = Pattern.compile("\\d{10}|(?:\\d{3}-){2}\\d{4}|\\(\\d{3}\\)\\d{3}-?\\d{4}");
        Matcher matcher = pattern.matcher(txtHomePhone.getText());
        
        boolean b = false;
        
        if (matcher.matches()) {
            b = true;
        } else {
            b = false;
        }
        
        return b;
    }
    
    private boolean ssnPatternCheck() {
        
        Pattern pattern = Pattern.compile("^(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}$");
        Matcher matcher = pattern.matcher(txtSSN.getText());
        
        boolean b = false;
        
        if (matcher.matches()) {
            b = true;
        } else {
            b = false;
        }
        
        return b;
    }
    
    private void autopopulateFields(Patient patient) {
        txtFirstName.setText(patient.getPatientFirstName());
        txtLastName.setText(patient.getPatientLastName());
        txtPatientIdentifier.setText(patient.getPatientId());
        txtHomePhone.setText(patient.getContactNumber());
        txtSSN.setText(patient.getSocialSecurityNumber());
        txtAge.setText(patient.getPatientAge());
        txtAddress.setText(patient.getAddress());
        txtPatientEmail.setText(patient.getPatientEmail());
        
        String sex = patient.getGender();
        
        if (sex.equals("Male")) {
            radioBtnMale.setSelected(true);
        } else if (sex.equals("Female")) {
            radioBtnFemale.setSelected(true);
        } else if (sex.equals("Other")) {
            radioBtnOther.setSelected(true);
        }
        
    }
    
    private boolean usernamePatternCorrect(String username) {
        Pattern p = Pattern.compile("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$");
        Matcher m = p.matcher(username);
        boolean b = m.matches();
        return b;
        
    }
    
    private boolean checkEmailDuplication(String patientEmail){
             boolean isPatientFound = false;
        String ssn = txtPatientSSN.getText().trim();
        List<Network> networks = ecosystem.getNetworks();
        List<HealthCenterEnterprise> healthCenterEnterprises = new ArrayList<>();
        
        for (Network network : networks) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HealthCenterEnterprise) {
                    healthCenterEnterprises.add((HealthCenterEnterprise) enterprise);
                }
            }
        }
        
        for (HealthCenterEnterprise healthCenterEnterprise : healthCenterEnterprises) {
            List<Patient> patients = healthCenterEnterprise.getPatientDirectory().getPatients();
            for (Patient patient : patients) {
                if (patientEmail.equals(patient.getPatientEmail())) {
                    isPatientFound = true;
                    break;
                }
                
            }
        }
        return isPatientFound;
    }
}
