/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ProfessorRole;

import Business.Course.Course;
import Business.Enterprise.Enterprise;
import Business.Enterprise.UniversityEnterprise;
//import Business.University.University;
import Business.Organization.ProfessorOrganization;
import Business.UserAccount.UserAccount;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vaishnavi
 */
public class AddCourseWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ProfessorOrganization pofessorOrganization;
    private UniversityEnterprise universityEnterprise;
    private String courseNumber;

    /**
     * Creates new form InsurancePolicyPlannerJPanel
     */
    public AddCourseWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ProfessorOrganization pofessorOrganization, Enterprise enterprise, String courseNumber) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.pofessorOrganization = pofessorOrganization;
        this.universityEnterprise = (UniversityEnterprise) enterprise;
        this.courseNumber = courseNumber;
        populateTable();
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        txtCourseNumber = new javax.swing.JTextField();
        txtMedicalPractice = new javax.swing.JTextField();
        lblMedicalPractice = new javax.swing.JLabel();
        txtRequirement = new javax.swing.JTextField();
        lblRequirement = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPolicies = new javax.swing.JTable();
        btnAddCourse = new javax.swing.JButton();
        lblObjective = new javax.swing.JLabel();
        txtLearningObjective = new javax.swing.JTextField();
        lblCourseNumber = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Skia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 79, 133));
        jLabel1.setText("Create a New Course");

        lblCourseName.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        lblCourseName.setForeground(new java.awt.Color(2, 79, 133));
        lblCourseName.setText("Course Name");

        txtCourseNumber.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        txtCourseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNumberActionPerformed(evt);
            }
        });

        txtMedicalPractice.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N

        lblMedicalPractice.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        lblMedicalPractice.setForeground(new java.awt.Color(2, 79, 133));
        lblMedicalPractice.setText("Medical Practice");

        txtRequirement.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N

        lblRequirement.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        lblRequirement.setForeground(new java.awt.Color(2, 79, 133));
        lblRequirement.setText("Requirement");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("%");

        jLabel6.setFont(new java.awt.Font("Skia", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 79, 133));
        jLabel6.setText("Course Work Area");

        tblPolicies.setBackground(new java.awt.Color(2, 79, 133));
        tblPolicies.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        tblPolicies.setForeground(new java.awt.Color(255, 255, 255));
        tblPolicies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Name", "Medical Practice", "Learning Objective", "Requirement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPolicies);

        btnAddCourse.setBackground(new java.awt.Color(2, 79, 133));
        btnAddCourse.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        btnAddCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCourse.setText("Create Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        lblObjective.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        lblObjective.setForeground(new java.awt.Color(2, 79, 133));
        lblObjective.setText("Learning Objective");

        txtLearningObjective.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N

        lblCourseNumber.setFont(new java.awt.Font("Skia", 1, 14)); // NOI18N
        lblCourseNumber.setForeground(new java.awt.Color(2, 79, 133));
        lblCourseNumber.setText("Course Number");

        txtCourseName.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMedicalPractice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblObjective, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRequirement, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCourseNumber, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddCourse)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedicalPractice, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLearningObjective, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(txtRequirement, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourseNumber)
                            .addComponent(txtCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourseName)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMedicalPractice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedicalPractice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLearningObjective, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObjective))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRequirement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRequirement))
                .addGap(18, 18, 18)
                .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
      private void refresh() {
        txtCourseNumber.setText(UUID.randomUUID().toString().substring(0, 7));
        txtCourseName.setText("");
        txtMedicalPractice.setText("");
        txtLearningObjective.setText("");
        txtRequirement.setText("");
    }
    
    private void populateFields() {
     txtCourseNumber.setText(courseNumber);
     return;
     }
    
    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        String courseName = txtCourseName.getText().trim();
        String medicalPractice = txtMedicalPractice.getText().trim();
        String learningObjective = txtLearningObjective.getText().trim();
        String requirement = txtRequirement.getText().trim();
        
        if (courseName.equals("")) {
            JOptionPane.showMessageDialog(null, "Course Name cannot be blank");
            return;
        }

        if (medicalPractice.equals("")) {
            JOptionPane.showMessageDialog(null, "Medical Practice cannot be blank");
            return;
        }

        if (learningObjective.equals("")) {
            JOptionPane.showMessageDialog(null, "Learning Objective cannot be blank");
            return;
        }

        if (requirement.equals("")) {
            JOptionPane.showMessageDialog(null, "Requirementcannot be blank");
            return;
        }

        double varRequirement = 0;
        try {
            varRequirement = Double.parseDouble(requirement);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Input");

            return;
        }

     
        Course course = new Course(courseNumber);
        course.setCourseName(courseName);
        course.setMedicalPractice(medicalPractice);
        course.setLearningObjective(learningObjective);
        course.setRequirement(varRequirement);
        
        
        universityEnterprise.getCourseDirectory().addNewCourse(course);
        JOptionPane.showMessageDialog(null, "Course added successfully");
        
        populateTable();
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void txtCourseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNumberActionPerformed

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPolicies.getModel();
        model.setRowCount(0);
        List<Course> courses = universityEnterprise.getCourseDirectory().getCourses();
        for (Course course : courses) {
            Object[] row = new Object[4];
            row[0] = course;
            row[1] = course.getMedicalPractice();
            row[2] = course.getLearningObjective();
            row[3] = course.getRequirement();
            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblPolicies.setRowSorter(sorter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseNumber;
    private javax.swing.JLabel lblMedicalPractice;
    private javax.swing.JLabel lblObjective;
    private javax.swing.JLabel lblRequirement;
    private javax.swing.JTable tblPolicies;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseNumber;
    private javax.swing.JTextField txtLearningObjective;
    private javax.swing.JTextField txtMedicalPractice;
    private javax.swing.JTextField txtRequirement;
    // End of variables declaration//GEN-END:variables

}
